# Site settings
title: Zachary Kessin 
email: zkessin@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Zachary Kessin is an erlang developer who has been building web applications for 20 years and 
  enjoys testing software with quickcheck

baseurl: "/zachkessin.com" # the subpath of your site, e.g. /blog/
url: "http://zachkessin.com" # the base hostname & protocol for your site
twitter_username: zkessin
github_username:  zkessin

# Build settings
markdown: kramdown
