# Site settings
title: Zachary Kessin 
email: zkessin@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
   If you want to enhance your development talk to me, I can
   help you with architecture, testing, development culture and best practices

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zachkessin.com" # the base hostname & protocol for your site
twitter_username: zkessin
github_username:  zkessin

# Build settings
markdown: kramdown


collections:
  targets:
    output: true
    permalink: /targets/:path/
    defaults:
      values:
        layout: page
  webinar:
    output: true
    permalink: /webinar/:path/
    defaults:
      values:
        layout: page
  classes:
    output: true
    permalink: /classes/:path/
    defaults:
      values:
        layout: page
  books:
    output: true
    permalink: /books/:path/
    defaults:
      values:
        layout: book
        price: 39
        site_price: 399